spring:
  application:
    name: portfolio

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
  
aws:
  region: ap-south-1
  dynamodb:
    table: portfolio
  sqs:
    message-queue-url: ${MESSAGE_QUEUE_URL}

server:
  servlet:
    context-path: /portfolio/api