spring:
  application:
    name: portfolio-service

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
  
aws:
  region: ${AWS_REGION}
  dynamodb:
    table-name: ${AWS_DYNAMODB_TABLE_NAME}
  sqs:
    message-queue-url: ${AWS_SQS_MESSAGE_QUEUE_URL}
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}

server:
  servlet:
    context-path: ${CONTEXT_PATH}